#!/bin/bash
mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

SECONDS=0

# some of my work
git config --global user.name "$gmail"
git config --global user.email "$CIRRUS_REPO_OWNER"

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/AOSPA/manifest -b topaz -g default,-mips,-darwin,-notdefault
git clone https://github.com/$MAIN_REPO/local_manifests.git --depth 1 -b topaz-wip .repo/local_manifests
# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# local manifest
git clone --depth=1 https://$CODER_REPO:$CODER_TOKEN@github.com/$CODER_REPO/device -b topaz-wip device/xiaomi/raphael
git clone --depth=1 https://$CODER_REPO:$CODER_TOKEN@github.com/$CODER_REPO/vendor -b topaz-wip vendor/xiaomi/raphael
git clone --depth=1 https://github.com/$MAIN_REPO/kernel_xiaomi_raphael.git -b topaz kernel/msm-4.14
#git clone --depth=1 https://$DEVICE_REPO:$DEVICE_TOKEN@github.com/$DEVICE_REPO/kernel_xiaomi_raphael -b backup kernel/msm-4.14
#git clone --depth=1 https://$CODER_REPO:$CODER_TOKEN@github.com/$CODER_REPO/prebuilt-kernel -b topaz device/xiaomi/raphael-kernel

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
