#!/bin/bash
mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

SECONDS=0

# some of my work
git config --global user.name "$gmail"
git config --global user.email "$CIRRUS_REPO_OWNER"

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/yaap/manifest.git -b thirteen -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# local manifest
git clone --depth=1 https://github.com/pwnrazr/device_xiaomi_raphael -b thirteen device/xiaomi/raphael
git clone --depth=1 https://github.com/pwnrazr/vendor_xiaomi_raphael -b thirteen vendor/xiaomi/raphael
git clone --depth=1 https://github.com/pwnrazr/kernel_raphael_sm8150 -b dev-pwn kernel/xiaomi/sm8150
git clone --depth=1 https://github.com/yaap/device_qcom_common -b thirteen device/qcom/common
git clone --depth=1 https://gitlab.com/yaosp/vendor_qcom_common -b thirteen vendor/qcom/common

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
